### ISSUE TITLE
User should switch between themes

### ISSUE THREAD

**Issue by Lenkly** [Lenkly/survey-app#17]
# What are the ressources?
Themes are defined and can be used with a simple button in the Appheader (emoji)

# ToDos
## User
- [x] Should have the choice to switch themes (a light one and a dark one)
- [ ] Might have a default theme according to the one one the phone (light or dark)

## Design
- [x] Switch button should be visible
- [ ] placement of the button should make sense (remove from the Appheader)
- [ ] design of the button should resemble the style of the theme
